language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

# before_script:
#   # https://github.com/npm/npm/issues/19019#issuecomment-341978497
#   - npm uninstall -g npm
#   - npx npmc install -g npm@5.3.x
#   - npx npmc install -g webpack grunt

script: npm run build

# Deployment with Github revision
# deploy:
#     provider: codedeploy
#     revision_type: github
#     access_key_id: $AWS_CI_ACCESS_KEY
#     secret_access_key: $AWS_CI_SECRET
#     application: miniature-bassoon
#     deployment_group: Test-EC2
#     region: us-west-2
#     on:
#       repo: PeteFromSales/miniature-bassoon

# Deployment to S3
deploy:
  # S3
  provider: s3
  access_key_id: $AWS_CI_ACCESS_KEY
  secret_access_key: $AWS_CI_SECRET
  bucket: miniature-bassoon
  region: us-east-1
  #prevent Travis CI from deleting your build artifacts
  skip_cleanup: true
  #
  # Code deploy
  provider: codedeploy
  access_key_id: $AWS_CI_ACCESS_KEY
  secret_access_key: $AWS_CI_SECRET
  bucket: miniature-bassoon
  key: "latest/miniature-bassoon.zip"
  application: miniature-bassoon
  deployment_group: Test-EC2
  region: us-west-2
  on:
    branch: master