language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

before_script:
  # https://github.com/npm/npm/issues/19019#issuecomment-341978497
  - npm uninstall -g npm
  - npm install -g webpack grunt

script: npm run build

deploy:
    provider: codedeploy
    revision_type: github
    access_key_id: $AWS_CI_ACCESS_KEY
    secret_access_key: $AWS_CI_SECRET
    application: miniature-bassoon
    deployment_group: Test-EC2
    region: us-west-2b
    on:
      repo: PeteFromSales/miniature-bassoon