language: node_js
node_js:
  - "node"
  - "8"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g webpack grunt

script: npm run build

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_CI_ACCESS_KEY
    secret_access_key: $AWS_CI_SECRET
    application: "miniature-bassoon"
    deployment_group: "Test-EC2"
    region: "us-west-2b"